### ISSUE TITLE
Alpha Testing Error

### ISSUE THREAD

**Issue by jruhterIllinois** [leakey-lab/Tool-For-Root-Image-Cleaning#2]
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'app'
 * Debug mode: on
WARNING: QApplication was not created in the main() thread.
QObject::moveToThread: Current thread (0x7524480037d0) is not the object's thread (0x75242c104580).
Cannot move to target thread (0x583a97d27c50)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/jeremy/Desktop/Tool-For-Root-Image-Cleaning/venv/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

**Comment by MasterKinjalk** [comment]
The issue could be resolved with using the appropriate installation of python with tkinter support as we have pivoted to it now.
